// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzU2Etbfcu4DoDYi3-i8zbVP0nHJetAo0',
    appId: '1:450524374566:web:c99478955cb774f340e8e7',
    messagingSenderId: '450524374566',
    projectId: 'mema-app-mobile',
    authDomain: 'mema-app-mobile.firebaseapp.com',
    storageBucket: 'mema-app-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOweouZvAbXhYTjcp2E_lB7EBPX9mJxF8',
    appId: '1:450524374566:android:2f0ca2d90d0a409740e8e7',
    messagingSenderId: '450524374566',
    projectId: 'mema-app-mobile',
    storageBucket: 'mema-app-mobile.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLbbg-gy2CaNhDl78z0V5J1osSz0lneoM',
    appId: '1:450524374566:ios:1099732c52b4ee1340e8e7',
    messagingSenderId: '450524374566',
    projectId: 'mema-app-mobile',
    storageBucket: 'mema-app-mobile.firebasestorage.app',
    iosBundleId: 'com.example.mema',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLbbg-gy2CaNhDl78z0V5J1osSz0lneoM',
    appId: '1:450524374566:ios:1099732c52b4ee1340e8e7',
    messagingSenderId: '450524374566',
    projectId: 'mema-app-mobile',
    storageBucket: 'mema-app-mobile.firebasestorage.app',
    iosBundleId: 'com.example.mema',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzU2Etbfcu4DoDYi3-i8zbVP0nHJetAo0',
    appId: '1:450524374566:web:a73f3fe6c827f5a640e8e7',
    messagingSenderId: '450524374566',
    projectId: 'mema-app-mobile',
    authDomain: 'mema-app-mobile.firebaseapp.com',
    storageBucket: 'mema-app-mobile.firebasestorage.app',
  );
}
